###
GET http://localhost:3000/api/samples
Origin: http://localhost:3000

###
GET http://localhost:3000/api/samples/CMI
Origin: http://localhost:3000

###
GET http://localhost:3000/api/samples/latest
Origin: http://localhost:3000

###
GET http://localhost:3000/api/samples/latest/2ab88a45-95a9-4a3f-b9ec-6c243d01dc65
Origin: http://localhost:3000

###
POST http://localhost:3000/api/samples/create
Origin: http://localhost:3000
Content-Type: application/json

[{
    "caseId": "6c44b527-20c3-428f-ab55-77f6aa6f750a",
    "orderId": "2ab88a45-95a9-4a3f-b9ec-6c243d01dc65"
},{
    "caseId": "24b2640a-9a2c-4bbb-a3a8-fbe8154a65b6",
    "orderId": "2ab88a45-95a9-4a3f-b9ec-6c243d01dc65"
}]

###
POST http://localhost:3000/api/samples/update
Origin: http://localhost:3000
Content-Type: application/json

{
    "orderId": "2ab88a45-95a9-4a3f-b9ec-6c243d01dc65",
    "bCode": "E100002",
    "afp": 1002.2,
    "conc": 41.5,
    "mainPeak": 167
}

###
POST http://localhost:3000/api/samples/update-extract
Origin: http://localhost:3000
Content-Type: application/json

{
    "orderId": "2ab88a45-95a9-4a3f-b9ec-6c243d01dc65",
    "bCode": "E100002",
    "extractedCheck": false,
    "extractedNote": "Low conc"
}

###
POST http://localhost:3000/api/samples/update-dist
Origin: http://localhost:3000
Content-Type: application/json

{
    "orderId": "2ab88a45-95a9-4a3f-b9ec-6c243d01dc65",
    "bCode": "E100002",
    "distRunCheck": false,
    "distRunNote": "Low input"
}

###
DELETE http://localhost:3000/api/samples/delete/d7ebb98a-f8b3-4fcc-a9a4-611f44275270
Origin: http://localhost:3000