###
POST http://localhost:8000/api/auth/sign-up/email
Origin: http://localhost:3000
Content-Type: application/json

{
  "name": "Moon",
  "email": "moo_sutthittha@hotmail.com",
  "password": "Moon148+-"
}

###
POST http://localhost:8000/api/auth/sign-in/email
Origin: http://localhost:3000
Content-Type: application/json

{
  "email": "moo_sutthittha@hotmail.com",
  "password": "Moon148+-"
}

###
POST http://localhost:8000/api/auth/sign-out
Origin: http://localhost:3000
Content-Type: application/json

{

}

###
POST http://localhost:8000/api/auth/change-password
Origin: http://localhost:3000
Content-Type: application/json

{
  "currentPassword": "Moon_148+-",
  "newPassword": "CEliver-test12+-"
}

###
POST http://localhost:8000/api/users/change-role
Origin: http://localhost:3000
Content-Type: application/json

{
  "userEmail": "moo_sutthittha@hotmail.com",
  "newRole": "admin"
}
