/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientOrderRouteImport } from './routes/client-order'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackingIndexRouteImport } from './routes/tracking/index'
import { Route as ReportIndexRouteImport } from './routes/report/index'
import { Route as AnalysisIndexRouteImport } from './routes/analysis/index'
import { Route as TrackingLotIdRouteImport } from './routes/tracking/$lotId'
import { Route as ReportSampleIdRouteImport } from './routes/report/$sampleId'
import { Route as AnalysisLotIdBCodeRouteImport } from './routes/analysis/$lotId.$bCode'

const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientOrderRoute = ClientOrderRouteImport.update({
  id: '/client-order',
  path: '/client-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingIndexRoute = TrackingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrackingRoute,
} as any)
const ReportIndexRoute = ReportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportRoute,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalysisRoute,
} as any)
const TrackingLotIdRoute = TrackingLotIdRouteImport.update({
  id: '/$lotId',
  path: '/$lotId',
  getParentRoute: () => TrackingRoute,
} as any)
const ReportSampleIdRoute = ReportSampleIdRouteImport.update({
  id: '/$sampleId',
  path: '/$sampleId',
  getParentRoute: () => ReportRoute,
} as any)
const AnalysisLotIdBCodeRoute = AnalysisLotIdBCodeRouteImport.update({
  id: '/$lotId/$bCode',
  path: '/$lotId/$bCode',
  getParentRoute: () => AnalysisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/client-order': typeof ClientOrderRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRouteWithChildren
  '/tracking': typeof TrackingRouteWithChildren
  '/report/$sampleId': typeof ReportSampleIdRoute
  '/tracking/$lotId': typeof TrackingLotIdRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/report/': typeof ReportIndexRoute
  '/tracking/': typeof TrackingIndexRoute
  '/analysis/$lotId/$bCode': typeof AnalysisLotIdBCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/client-order': typeof ClientOrderRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report/$sampleId': typeof ReportSampleIdRoute
  '/tracking/$lotId': typeof TrackingLotIdRoute
  '/analysis': typeof AnalysisIndexRoute
  '/report': typeof ReportIndexRoute
  '/tracking': typeof TrackingIndexRoute
  '/analysis/$lotId/$bCode': typeof AnalysisLotIdBCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/client-order': typeof ClientOrderRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRouteWithChildren
  '/tracking': typeof TrackingRouteWithChildren
  '/report/$sampleId': typeof ReportSampleIdRoute
  '/tracking/$lotId': typeof TrackingLotIdRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/report/': typeof ReportIndexRoute
  '/tracking/': typeof TrackingIndexRoute
  '/analysis/$lotId/$bCode': typeof AnalysisLotIdBCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analysis'
    | '/client-order'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/report'
    | '/tracking'
    | '/report/$sampleId'
    | '/tracking/$lotId'
    | '/analysis/'
    | '/report/'
    | '/tracking/'
    | '/analysis/$lotId/$bCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/client-order'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/report/$sampleId'
    | '/tracking/$lotId'
    | '/analysis'
    | '/report'
    | '/tracking'
    | '/analysis/$lotId/$bCode'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analysis'
    | '/client-order'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/report'
    | '/tracking'
    | '/report/$sampleId'
    | '/tracking/$lotId'
    | '/analysis/'
    | '/report/'
    | '/tracking/'
    | '/analysis/$lotId/$bCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalysisRoute: typeof AnalysisRouteWithChildren
  ClientOrderRoute: typeof ClientOrderRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportRoute: typeof ReportRouteWithChildren
  TrackingRoute: typeof TrackingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-order': {
      id: '/client-order'
      path: '/client-order'
      fullPath: '/client-order'
      preLoaderRoute: typeof ClientOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/': {
      id: '/tracking/'
      path: '/'
      fullPath: '/tracking/'
      preLoaderRoute: typeof TrackingIndexRouteImport
      parentRoute: typeof TrackingRoute
    }
    '/report/': {
      id: '/report/'
      path: '/'
      fullPath: '/report/'
      preLoaderRoute: typeof ReportIndexRouteImport
      parentRoute: typeof ReportRoute
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/tracking/$lotId': {
      id: '/tracking/$lotId'
      path: '/$lotId'
      fullPath: '/tracking/$lotId'
      preLoaderRoute: typeof TrackingLotIdRouteImport
      parentRoute: typeof TrackingRoute
    }
    '/report/$sampleId': {
      id: '/report/$sampleId'
      path: '/$sampleId'
      fullPath: '/report/$sampleId'
      preLoaderRoute: typeof ReportSampleIdRouteImport
      parentRoute: typeof ReportRoute
    }
    '/analysis/$lotId/$bCode': {
      id: '/analysis/$lotId/$bCode'
      path: '/$lotId/$bCode'
      fullPath: '/analysis/$lotId/$bCode'
      preLoaderRoute: typeof AnalysisLotIdBCodeRouteImport
      parentRoute: typeof AnalysisRoute
    }
  }
}

interface AnalysisRouteChildren {
  AnalysisIndexRoute: typeof AnalysisIndexRoute
  AnalysisLotIdBCodeRoute: typeof AnalysisLotIdBCodeRoute
}

const AnalysisRouteChildren: AnalysisRouteChildren = {
  AnalysisIndexRoute: AnalysisIndexRoute,
  AnalysisLotIdBCodeRoute: AnalysisLotIdBCodeRoute,
}

const AnalysisRouteWithChildren = AnalysisRoute._addFileChildren(
  AnalysisRouteChildren,
)

interface ReportRouteChildren {
  ReportSampleIdRoute: typeof ReportSampleIdRoute
  ReportIndexRoute: typeof ReportIndexRoute
}

const ReportRouteChildren: ReportRouteChildren = {
  ReportSampleIdRoute: ReportSampleIdRoute,
  ReportIndexRoute: ReportIndexRoute,
}

const ReportRouteWithChildren =
  ReportRoute._addFileChildren(ReportRouteChildren)

interface TrackingRouteChildren {
  TrackingLotIdRoute: typeof TrackingLotIdRoute
  TrackingIndexRoute: typeof TrackingIndexRoute
}

const TrackingRouteChildren: TrackingRouteChildren = {
  TrackingLotIdRoute: TrackingLotIdRoute,
  TrackingIndexRoute: TrackingIndexRoute,
}

const TrackingRouteWithChildren = TrackingRoute._addFileChildren(
  TrackingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalysisRoute: AnalysisRouteWithChildren,
  ClientOrderRoute: ClientOrderRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportRoute: ReportRouteWithChildren,
  TrackingRoute: TrackingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
